# Generated by Django 4.2.4 on 2023-08-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
